# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'aziotmobile' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # React
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTGeolocation',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # End React
  pod 'ADAL', '~> 4.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-torch', :path => '../node_modules/react-native-torch'

  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

end
